### ISSUE TITLE
SolidStart/SSR support

### ISSUE THREAD

**Issue by davedbase** [GIShub4/solid-map-gl#12] opened 2022-09-04 15:55 UTC
Hi there! Me again =) I'm trying to use solid-map-gl on a Solid 1.5 project with SolidStart (alpha-100). I dropped in the sample component and got a massive error:

```ts
import { Component, createSignal } from "solid-js";
import MapGL, { Viewport, Source, Layer } from "solid-map-gl";

const Map: Component = () => {
  const [viewport, setViewport] = createSignal({
    center: [-122.45, 37.78],
    zoom: 11,
  } as Viewport);
  return (
    <MapGL
      options={{
        accessToken: import.meta.env.VITE_MAPBOX_ACCESS_TOKEN,
        style: "mb:light",
      }}
      viewport={viewport()}
    >
      <Source
        source={{
          type: "geojson",
          data: "https://docs.mapbox.com/mapbox-gl-js/assets/earthquakes.geojson",
        }}
      >
        <Layer
          style={{
            type: "circle",
            source: "earthquakes",
            paint: {
              "circle-radius": 8,
              "circle-color": "red",
            },
          }}
        />
      </Source>
    </MapGL>
  );
};

export default Map;
```
Resulting error due to CJS exports not existing.
```
SyntaxError: Named export 'MercatorCoordinate' not found. The requested module 'mapbox-gl' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'mapbox-gl';
```
I typically recommend using https://github.com/solidjs-community/rollup-preset-solid as a starting point for properly exporting libraries like this. With SolidStart becoming more stable the need for proper exports is important as well.

=)

**Comment by KaiHuebner** [comment] 2022-09-10 01:00
Hi Dave,
That's a tricky one. I get the same error message when I use [solid-start](https://github.com/solidjs/solid-start).
The problem is with MapBox not using named export: https://github.com/mapbox/mapbox-gl-js/issues/8676
We had a similar issue before: https://github.com/GIShub4/solid-map-gl/issues/6

I'm already using [rollup-preset-solid](https://github.com/solidjs-community/rollup-preset-solid) in [rollup.config.js](https://github.com/GIShub4/solid-map-gl/blob/main/rollup.config.js). But that doesn't include dependent libraries.

One option would be to include the MapBox library in the rollup config. But that would increase this library and lock it to a specific MapBox version.

Can you think of a better solution?

**Comment by trusktr** [comment] 2022-09-10 17:02
This line breaks away from patterns and is not importing from src:

https://github.com/GIShub4/solid-map-gl/blob/2c43060babb6a847470fd67c467c3c618332be32/src/components/Camera/index.tsx#L5

That should fix the problem (make sure everything imports directly from src folder)

**Comment by KaiHuebner** [comment] 2022-09-10 22:21
Thanks @trusktr for your help, that was the issue.
It's fixed now and works with solid-start.

**Closed by KaiHuebner** 2022-09-10 22:21 UTC

**Comment by davedbase** [comment] 2022-09-12 20:56
Awesome. I just pulled it into my codebase and gave it a spin but I got an instant error:
```
SyntaxError: The requested module 'solid-js/web' does not provide an export named 'classList'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:128:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:194:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:409:24)
    at async nodeImport (file:///Users/ddibiase/Projects/roma/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50619:21)
    at async eval (/src/components/Map.tsx:7:31)
    at async instantiateModule (file:///Users/ddibiase/Projects/roma/node_modules/vite/dist/node/chunks/dep-0fc8e132.js:50548:9)
4:45:33 p.m. [vite] page reload src/components/Map.tsx
```
Not doing anything special. Just importing and using the example in my route in SolidStart. I also have it set as noExternal.

**Comment by KaiHuebner** [comment] 2022-09-15 11:41
Hi @davedbase,
I can't replicate the issue. Can you please tell me more on how do you create your app.
Are you using `pnpm`? What options are you using in `solid start`?
